### ISSUE TITLE
Better distinguish voter/votee in tally

### ISSUE THREAD

**Issue by Sigafoos** [awoo-detat/awoo#11]
Ideally we'd see something like

    Dan (2): Doman, Teakwood
    Doman (1): Dan
    Teakwood (0)
    Julia (0)
    Matt (0)

**Comment by segfaultvicta** [comment]
It should... already be doing this, but the UX for it probably sucks and needs to be a lot more clear.

**Comment by Sigafoos** [comment]
That is the case, I think. Not that the UX sucks but that it needs to be clearer. Bolding the candidate is probably sufficient? And maybe shrink the font size of the voters.

**Comment by segfaultvicta** [comment]
hurray that was my wild-ass stab at what would actually make it usabler. shush your nose Chrome 'usabler' is a word now

**Comment by Sigafoos** [comment]
Fixed in 5baa201
